site_name: Gerador de Sites com CrewAI
theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist
  - admonition
  - footnotes

nav:
  - Início: index.md
  - Guia:
    - Instalação: guia/instalacao.md
    - Uso: guia/uso.md
  - Exemplos:
    - Sites Gerados: exemplos/sites.md
  - Sobre:
    - Contribuição: sobre/contribuicao.md